version: '2.4'

services:
  app:
    build:
      context: .
      target: build
    command: yarn dev
    env_file: .env
    networks:
      - db-net
      - redis-net
    ports:
      - 3333:3333
    volumes:
      - ./:/home/node/app:delegated
    depends_on:
      - db
      - redis

  queue-manager:
    build:
      context: .
      target: build
    command: yarn queue
    env_file: .env
    networks:
      - redis-net
    volumes:
      - ./:/home/node/app:delegated
    depends_on:
      - redis

  db:
    image: postgres:11
    env_file: .env
    networks:
      - db-net
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    env_file: .env
    networks:
      - redis-net

networks:
  db-net:
  redis-net:

volumes:
  db:
